import './onscroll.js'
import './navbar.js'
import './styles/main.scss'
import hero from './assets/hero-png.jpg'
import ceviche from './assets/ceviche.jpg'
import lomo from './assets/lomo-saltado.jpg'
import pollo from './assets/pollo.jpg'
import papa from './assets/papa.jpg'
import peru from './assets/peruvian.jpg'
import causa from './assets/causa.jpeg'